plugins {
    id 'com.android.application'
}

android {
    namespace 'kr.co.seongsamgukji.nativeprobe'
    compileSdk 35

    defaultConfig {
        applicationId 'kr.co.seongsamgukji.nativeprobe'
        minSdk 26
        targetSdk 35
        versionCode 118
        versionName '4.77.0'
    }
}

dependencies {
}
